# Generated by Django 3.0.2 on 2020-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('suggested_url_suffix', models.CharField(blank=True, max_length=10)),
                ('generated_url', models.URLField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
