# Generated by Django 3.0.2 on 2020-01-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='generate_url_suffix',
            new_name='generated_url_suffix',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='suggested_url_suffix',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
