# Generated by Django 3.0.2 on 2020-01-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20200110_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='generated_url_suffix',
            new_name='generated_url',
        ),
    ]
